"""add_trip_coordinates_and_route_cache

Revision ID: 22d9cb8ab283
Revises: 3f39ce8a4ec2
Create Date: 2026-09-24 02:26:47.936813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d9cb8ab283'
down_revision: Union[str, Sequence[str], None] = '3f39ce8a4ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('origin_name', sa.String(), nullable=True),
    sa.Column('dest_name', sa.String(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('geometry_json', sa.String(), nullable=False),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_cache_cache_key'), 'route_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_route_cache_id'), 'route_cache', ['id'], unique=False)
    op.create_table('gps_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('heading_degrees', sa.Float(), nullable=False),
    sa.Column('ignition_on', sa.Boolean(), nullable=False),
    sa.Column('fuel_level_pct', sa.Float(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gps_locations_id'), 'gps_locations', ['id'], unique=False)
    op.add_column('trips', sa.Column('origin_lat', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('origin_lng', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('dest_lat', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('dest_lng', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('route_geometry', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'route_geometry')
    op.drop_column('trips', 'dest_lng')
    op.drop_column('trips', 'dest_lat')
    op.drop_column('trips', 'origin_lng')
    op.drop_column('trips', 'origin_lat')
    op.drop_index(op.f('ix_gps_locations_id'), table_name='gps_locations')
    op.drop_table('gps_locations')
    op.drop_index(op.f('ix_route_cache_id'), table_name='route_cache')
    op.drop_index(op.f('ix_route_cache_cache_key'), table_name='route_cache')
    op.drop_table('route_cache')
    # ### end Alembic commands ###
